# Configuración Enterprise de Brave Cleaner
# Versión: 2.0 - Enterprise Grade

# Configuración de logging enterprise
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "brave_cleaner.log"
  max_size: 10485760  # 10MB
  backup_count: 5
  structured_logging: true
  console_colors: true
  log_rotation: true

# Configuración de seguridad enterprise
security:
  secure_delete: true
  secure_delete_passes: 3
  secure_delete_verify: true
  verify_permissions: true
  check_file_integrity: true
  max_retries: 3
  
  process_detection:
    enabled: true
    timeout_seconds: 30
    force_termination: false
    detect_child_processes: true
    validate_process_integrity: true
  
  file_validation:
    validate_sqlite_integrity: true
    check_file_signatures: true
    prevent_system_file_deletion: true
    max_file_size_mb: 1000
  
  file_protection:
    detect_locked_files: true
    handle_protected_files: true
    respect_system_protections: true
    preserve_critical_files: true
  
  path_sanitization:
    enabled: true
    prevent_path_traversal: true
    validate_path_integrity: true

# Configuración de backup enterprise
backup:
  enabled: true
  directory: "backups"
  compression: true
  max_backups: 10
  auto_cleanup: true
  
  transaction:
    enabled: true
    auto_rollback: true
    snapshot_before_cleanup: true
    verify_snapshot_integrity: true
  
  types:
    full: true
    incremental: true
    pre_cleanup: true
  
  integrity:
    verify_backup_integrity: true
    calculate_backup_hash: true
    verify_restore_integrity: true
  
  cleanup:
    max_age_days: 30
    max_size_gb: 10
    preserve_recent: 3

# Configuración de limpieza enterprise
cleaning:
  dry_run: false
  confirm_destructive: true
  parallel_operations: true
  max_workers: 4
  
  safety:
    require_confirmation: true
    max_file_size_mb: 1000
    backup_before_delete: true
    validate_targets: true
  
  components:
    browsing_data:
      history: true
      cookies: true
      cache: true
      downloads: true
      form_data: true
      passwords: true
      autofill: true
      site_data: true
    
    extensions:
      enabled: true
      data: true
      settings: true
    
    preferences:
      settings: true
      bookmarks: false
      shortcuts: true
      search_engines: true
    
    rewards:
      wallet: true
      tokens: true
      ads_data: true
      contributions: true
    
    sync:
      sync_data: true
      encryption_keys: true
      sync_settings: true
    
    storage:
      local_storage: true
      session_storage: true
      indexed_db: true
      web_sql: true
      cache_storage: true
    
    logs:
      crash_reports: true
      debug_logs: true
      performance_logs: true
      network_logs: true
    
    certificates:
      ssl_certificates: true
      client_certificates: true
      certificate_errors: true

# Rutas enterprise de Brave
brave_paths:
  windows:
    - "%LOCALAPPDATA%/BraveSoftware/Brave-Browser/User Data"
    - "%APPDATA%/BraveSoftware/Brave-Browser/User Data"
    - "%PROGRAMFILES%/BraveSoftware/Brave-Browser/User Data"
    - "%PROGRAMFILES(X86)%/BraveSoftware/Brave-Browser/User Data"
  
  macos:
    - "~/Library/Application Support/BraveSoftware/Brave-Browser"
    - "/Applications/Brave Browser.app/Contents/Resources"
  
  linux:
    - "~/.config/BraveSoftware/Brave-Browser"
    - "~/.local/share/BraveSoftware/Brave-Browser"
    - "/opt/brave.com/brave"
    - "/usr/share/brave-browser"

# Variantes enterprise de Brave
brave_variants:
  - "Brave-Browser"
  - "Brave-Browser-Beta"
  - "Brave-Browser-Dev"
  - "Brave-Browser-Nightly"
  - "Brave-Browser-Portable"

# Configuración enterprise corporativa
enterprise:
  respect_gpo: true
  preserve_certificates: true
  preserve_enterprise_settings: true
  
  corporate:
    preserve_bookmarks: false
    preserve_extensions: false
    preserve_passwords: false
    preserve_cookies: false
  
  domain:
    check_domain_policies: true
    respect_domain_restrictions: true
    preserve_domain_certificates: true

# Configuración de análisis enterprise
analysis:
  pre_cleanup_analysis: true
  post_cleanup_verification: true
  generate_detailed_reports: true
  
  security_analysis:
    scan_for_malware: false
    check_file_permissions: true
    validate_file_integrity: true
    detect_suspicious_activity: true
  
  metrics:
    track_cleaning_performance: true
    measure_storage_impact: true
    log_operation_times: true
    generate_statistics: true

# Configuración de UI enterprise
ui:
  colors: true
  progress_bars: true
  verbose_output: false
  show_warnings: true
  confirm_actions: true
  wait_for_exit: true
  
  output:
    format: "text"
    include_timestamps: true
    include_system_info: true
    include_performance_metrics: true

# Configuración de testing enterprise
testing:
  dry_run_mode: false
  simulate_operations: false
  validate_configuration: true
  test_file_permissions: true
  verify_backup_system: true
  
  auto_test:
    enabled: false
    test_after_cleanup: true
    verify_brave_startup: true
    check_data_integrity: true

# Configuración de monitoreo enterprise
monitoring:
  advanced_logging: true
  log_performance_metrics: true
  log_security_events: true
  
  alerts:
    enabled: false
    critical_errors: true
    security_violations: true
    backup_failures: true
  
  telemetry:
    enabled: false
    collect_usage_stats: false
    send_error_reports: false

# Configuración de rendimiento enterprise
performance:
  parallel_processing: true
  max_workers: 4
  chunk_size: 1024
  
  io_optimization:
    buffer_size: 8192
    use_memory_mapping: false
    optimize_for_large_files: true
  
  memory_management:
    max_memory_usage_mb: 512
    cleanup_memory_after_operations: true
    use_streaming_for_large_files: true

# Configuración de recuperación enterprise
recovery:
  auto_recovery: true
  max_recovery_attempts: 3
  auto_rollback: true
  rollback_on_critical_error: true
  post_operation_verification: true
  verify_brave_functionality: true

# Configuración de compatibilidad enterprise
compatibility:
  supported_versions:
    min_version: "1.0.0"
    max_version: "999.999.999"
  
  supported_os:
    windows: ["10", "11"]
    macos: ["10.14", "11", "12", "13"]
    linux: ["ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04", "centos:7", "centos:8"]
  
  supported_architectures:
    - "x86_64"
    - "amd64"
    - "arm64"

# Configuración de auditoría enterprise
audit:
  audit_logging: true
  log_all_operations: true
  log_file_access: true
  
  traceability:
    generate_operation_ids: true
    log_user_actions: true
    track_file_modifications: true
  
  compliance:
    gdpr_compliance: false
    sox_compliance: false
    hipaa_compliance: false 